theme: Minima
title: Hello Coding X
author: RitabrataX
email: your-email@domain.com
description: > # This is going to be a great event.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
